---
# Deploy to the registry. At the moment it is necessary to manually pull.
# This will be added by copying the CD code from makibot or makigas.es
# once the system is fully working.

name: CD
on:
  workflow_run:
    workflows:
      - CI
    branches:
      - trunk
    types:
      - completed
jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Release Docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}/early:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
