---
# Deploy frozen versions to the registry on tag release.

name: Release
on:
  release:
    types:
      - published
jobs:
  release:
    name: Release Docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Capture version code
        id: version
        run: echo ::set-output name=code::${GITHUB_REF#refs/*/}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}/early:${{ steps.version.outputs.code }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
